[package]
name = "boltpm-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "1" }
serde = { version = "1", features = ["derive"] }
serde_json = "1" 

[build-dependencies]
tauri-build = "1.4" 