[package]
productName = "BoltPM Desktop"
version = "0.1.0"

[build]
beforeBuildCommand = ""
beforeDevCommand = ""
devPath = "src/frontend"
distDir = "src/frontend"

[tauri]
identifier = "com.boltpm.desktop"

  [[tauri.windows]]
  title = "BoltPM Desktop"
  width = 800
  height = 600
