[package]
name = "test_project"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
tempfile = "3"
reqwest = { version = "0.11", features = ["blocking", "multipart"] }
serde_json = "1.0"
